// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourOfHeroes.Data;

#nullable disable

namespace TourOfHeroes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231015154902_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TourOfHeroes.Models.Hero", b =>
                {
                    b.Property<int>("HeroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeroID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HeroID");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            HeroID = 12,
                            Name = "Dr. Nice"
                        },
                        new
                        {
                            HeroID = 13,
                            Name = "Bombasto"
                        },
                        new
                        {
                            HeroID = 14,
                            Name = "Celeritas"
                        },
                        new
                        {
                            HeroID = 15,
                            Name = "Magneta"
                        },
                        new
                        {
                            HeroID = 16,
                            Name = "RubberMan"
                        },
                        new
                        {
                            HeroID = 17,
                            Name = "Dynama"
                        },
                        new
                        {
                            HeroID = 18,
                            Name = "Dr. IQ"
                        },
                        new
                        {
                            HeroID = 19,
                            Name = "Magma"
                        },
                        new
                        {
                            HeroID = 20,
                            Name = "Tornado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
